server:
  port: 9191
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: https-uuid-client\uuidclient.p12
    key-store-password: 123456
    key-alias: uuidclient

truststore:
  store: classpath:keystore/truststore.p12
  password: 123456

uuid:
  service:
    url: https://localhost:8181/api/uuid
